### ISSUE TITLE
CN301 

### ISSUE THREAD

**Issue by trev347** [kpishere/homie_heatPump#1]
Great work but just wondering the wiring for the CN301 port the only instructions I see are for the display port the CN201 or was the CN301 a typo? Thank you

**Comment by kpishere** [comment]
I'm, i'll revisit and get back to you.  Can never bee too sure.  The key difference is that one of them has a clock, data, and three 'trigger' signals if you will (for LED 1, LED 2, and the other LEDs).  Other than that, they are effectively the same.  To summarize, there is a connector for wired remote that is isolated optically, one that is a wired remote (I think for the 'wireless WIFI option), and then the one that goes to the internal control board.  All of them have the same pulse trigger signal that comes from handheld remote.

**Comment by kpishere** [comment]
Yeah, checked (have u looked at wiki page? hi res pics there). CN201 is the cnxn from display to inside board. I've replaced mine with this project here but i expect most dont want that.  CN301 is for a wired connection - if u use this one you'll get the remote signal too if u still use that. CN101 is for an optio isolated wall control. It does not get signals if IR remote is used. Clear?

**Comment by trev347** [comment]
Right now I have it connected to the CN201 With a Y-connector and I’m getting a control response but not sure how to send a post to it to turn it on or off or change temperature
