### ISSUE TITLE
MQTT POST

### ISSUE THREAD

**Issue by trev347** [kpishere/homie_heatPump#2]
Can you also give a example of MQTT post to set temperature and fan speed or just examples in general I plan on using this with openHAB. Thank you

**Comment by kpishere** [comment]
Ah, if this is new to you, there is this thing about homie, 'the homie convention'. that describes how to send a command to a device. There is link in this readme and i also just added an example of a command at end too in response.  more detailed documentation at https://homieiot.github.io/homie-esp8266/  Note this project has no dependencies on homie, in that case the arduino script serves as reference for how to use ( in homie_heatPump.ino the method propertyHandler() parses a command string which is same syntax as is in status format)
